name: Workflow Practice

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs: 
  linux_practise:
    runs-on: ubuntu-Latest

    steps:
      - name: checkout
        run: ls -la
      - name: checkout code
        uses: actions/checkout@v3
      - name: list files
        run: ls -la
      - name: Add a yml file
        run: |
          cd .github/workflows
          touch main2.yml
          sleep 10
      
      - name: List files again
        run: |
          ls -la .github/workflows
          sleep 10
        
      - name: add text to file
        run: |
          cd .github/workflow/main2.yml
          echo "heelo k n " >> main2.yml
          sleep 10
      - name: change the chmod
        run: |
          cd .github/workflow/main2.yml
          chmod +x main2.yml
          bash main2.yml
          sleep 10
      

 

       
