name: Workflow Practice

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs: 
  linux_practise:
    runs-on: ubuntu-Latest

    steps:
      - name: checkout
        run: ls -l

      - name: checkout code
        uses: actions/checkout@v4

      - name: list files
        run: ls -l

      - name: Add a yml file and text to it
        run: |
          cd .github/workflows
          touch main2.yml
          ls  -l
          sleep 10
          
          echo "heelo" >main2.yml
          sleep 10
      
      - name: List files again
        run: |
          ls -l .github/workflows
          sleep 10
        
      
      

 

       
